### ISSUE TITLE
老文章访问不了

### ISSUE THREAD

**Issue by standin000** [uglyboy-tl/uglyboy-tl.github.io#1]
https://blog.uglyboy.cn/post/autorestic/  这篇文章404了

**Comment by uglyboy-tl** [comment]
> https://blog.uglyboy.cn/post/autorestic/ 这篇文章404了

本是打算把之前的文章都清空的。。。这篇给恢复了哈，不过网址有点小变化：https://blog.uglyboy.cn/posts/autorestic/
